# Network Configuration
[network]
rpc_url = "http://127.0.0.1:8545"
chain_id = 31337

# Deployment Configuration
[deployment]
private_key = "your_private_key_here"
deployer_address = "your_deployer_address_here"

# Gas Configuration
[gas]
gas_limit = 500000
gas_price = 20000000000

# Contract Configuration
[contract]
name = "ERC7730CommunityReview"
version = "1.0.0"

# Optional: Etherscan API Key for verification
[verification]
etherscan_api_key = "your_etherscan_api_key_here"

# Optional: Alchemy API Key
[alchemy]
api_key = "your_alchemy_api_key_here"
